# Generated by Django 5.0.3 on 2024-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_class_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='level',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], max_length=10),
        ),
    ]
