# Generated by Django 5.0.3 on 2024-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_difficultylevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], max_length=10),
        ),
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
    ]
