# Generated by Django 5.0.3 on 2024-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='Questions.topic'),
        ),
        migrations.AddField(
            model_name='standard',
            name='subjects',
            field=models.ManyToManyField(related_name='standards', to='Questions.subject'),
        ),
    ]
