# Generated by Django 5.0.3 on 2024-05-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_alter_question_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_json', models.JSONField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.chapter')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.subject')),
                ('topics', models.ManyToManyField(to='Questions.topic')),
            ],
        ),
    ]
