# Generated by Django 5.0.3 on 2024-05-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_questionpaper_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.CharField(choices=[('descriptive', 'Descriptive'), ('objective', 'Objective'), ('both', 'Both')], max_length=11)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_tests', to='Questions.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tests', to='Questions.subject')),
            ],
        ),
    ]
