# Generated by Django 5.0.3 on 2024-05-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_questionpapers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionPapers',
            new_name='QuestionPaper',
        ),
    ]
