# Generated by Django 5.0.3 on 2024-05-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_rename_questionpapers_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.chapter'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='topics',
            field=models.ManyToManyField(blank=True, to='Questions.topic'),
        ),
    ]
