# Generated by Django 5.0.3 on 2024-06-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_entrancetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('parents_name', models.CharField(blank=True, max_length=255)),
                ('parents_phone_number', models.CharField(blank=True, max_length=15)),
                ('highest_qualification', models.CharField(blank=True, max_length=255)),
                ('educational_institution', models.CharField(blank=True, max_length=255)),
                ('year_of_completion', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('entrance_test_applied_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.entrancetest')),
            ],
            options={
                'verbose_name_plural': 'candidates',
            },
        ),
    ]
