# Generated by Django 5.0.3 on 2024-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_alter_questionpaper_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
