# Generated by Django 5.0.3 on 2024-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default=2000, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
    ]
