# Generated by Django 5.0.3 on 2024-05-05 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_questionpaper_question_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
