# Generated by Django 5.0.3 on 2024-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_alter_candidate_address_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='admin', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
