# Generated by Django 5.0.3 on 2024-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_questionpaper_created_at_questionpaper_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='question_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
