# Generated by Django 5.0.3 on 2024-04-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_question_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='class_level',
            new_name='standard',
        ),
    ]
